# Apply label "feature" if head matches "feature/*"
ğŸ¾ New Feature:
  head: ["feature/*", "feat/*"]

# Apply label "bugfix" if head matches one of "bugfix/*" or "hotfix/*"
ğŸ› Bug fix:
  head: ["bugfix/*", "hotfix/*", "fix/*"]

ğŸ“– Documentation:
  head: "docs/*"

ğŸ›  CI:
  head: "ci/*"

ğŸ“¦ Build:
  head: "build/*"

ğŸ”¨ Refactor:
  head: "refactor/*"

ğŸ“ Test:
  head: "test/*"

ğŸ€ Style:
  head: "style/*"

ğŸš˜ Performance:
  head: "perf/*"

ğŸŒ¾ Chore:
  head: "chore/*"
